### ISSUE TITLE
Hint message doesn't show, notification sometimes spams

### ISSUE THREAD

**Issue by t18n** [m4xshen/hardtime.nvim#18]
First off, I am new to Nvim and this is probably the most useful plugin I found that force me to use Nvim more efficiently. So thank you so much for your work.

I am using LazyVim config and use the standard `hardtime` settings, with both `hint` and `notification` enabled. However, I cannot see the hint messages anywhere.

Another issue is that the notifications seems to be triggered everytime I click anything. Also, with `disable_mouse` enable, when I scroll down on my mouse (muscle memorry), the screen is filled with notifications, treating it like key `DOWN` button. Maybe we could add an option debounce it?
![image](https://github.com/m4xshen/hardtime.nvim/assets/14198542/1f4b968f-6d76-4d0b-91ff-35f548ef1f28)

**Comment by m4xshen** [comment]
Thanks!
Are you using the latest version? Now the `event = "VeryLazy"` is not reqired any more. Please remove it and try again.

**Comment by m4xshen** [comment]
For the second issue, it is actually same as #7 and I fixed it with `notification` option.

**Comment by m4xshen** [comment]
Hey, @t18n, does the issue still exist?

**Comment by t18n** [comment]
@m4xshen I am so sorry for the late reply and thank you for the responses. Removing `VeryLazy` did not fix it. Setting `notification=false` just disable all notification at once, which is fine by me, but quite confusing sometimes, since for some reason my `Hints` are not displayed on the lualine.
